// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tovkltnfqkjsdbuzalbk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRvdmtsdG5mcWtqc2RidXphbGJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxMjcxNjAsImV4cCI6MjA1ODcwMzE2MH0.e-QYAi5ThakwcOmtp5QBLmrp6qTgCVZUHwN_l3IEeSw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);